networks:
  default:
    name: 'test-auth'

volumes:
  db-data:

services:
  db:
    container_name: 'test-auth-db'
    image: postgres:16-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: public
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5011:5432"


  api:
    container_name: 'test-auth-api'
    image: 'test-auth-api'
    build:
      context: ../
      dockerfile: src/TestAuth.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:5010
    ports:
      - "5010:5010"

  front:
    container_name: "test-auth-front"
    image: 'test-auth-front'
    build:
      context: ../src/TestAuth.Api/Client
      dockerfile: /Dockerfile
      args:
        - BASE_URL=api:5010
    ports:
      - '5012:3000'
